### PR TITLE
Use Requirements-Builder and Tox for testing.

### PR DESCRIPTION
**Pull request by greut**
[Requirements-Builder](http://pythonhosted.org/requirements-builder/) is a tools that will test against the lowest, current and highest version of all your dependencies. On travis and locally via `tox`. Good stuff.

**blockers**
- [x] https://github.com/inveniosoftware/requirements-builder/pull/16
- [x] https://github.com/inveniosoftware/requirements-builder/pull/17

### CODE REVIEW

**Comment by azaroth42** [comment]
Unfortunately the IIIF web server runs on a machine with python 2.6 ... so we can't just drop support for it.

**Comment by greut** [comment]
@azaroth42 it shouldn't be the case. A good old RHEL? ;-)

**Comment by azaroth42** [comment]
Yep, ouR HELl indeed. Until the machine gets updated, we're stuck with supporting 2.6.

**Comment by greut** [comment]
The build is green.

**Comment by zimeon** [comment]
Thanks @greut , this looks good to me. @azaroth42 - I'm :+1: on merging, you?

Agreeing with past comments I think we should keep support for py2.6 for a bit as RHEL is not uncommon and it may affect others as well as the iiif.io server

**Pull request merged**
